# Global settings
replicaCount: 1

# Image definitions
images:
  backend: learning-server
  frontend: learning-client
  pullPolicy: IfNotPresent

# Vault Configuration (Bootstrap)
vault:
  address: "http://vault-internal:8200"
  token: "hvs.your_vault_token"

# Backend Configuration
backend:
  serviceName: backend-service
  port: 5000

# Frontend Configuration
frontend:
  serviceName: frontend-service
  port: 3000

# Istio Configuration (The Cockpit Entry Point)
istio:
  enabled: true
  gatewayName: "learning-gateway"
  # In production, change "*" to your domain
  host: "*"

# Monitoring
monitoring:
  prometheusEnabled: true
  grafanaEnabled: true